// src/components/BlogPreview.svelte
<script>
  export let slug
  export let title
  export let excerpt
  export let pubDate

  const formattedDate = new Date(pubDate).toDateString()
</script>

<div class="prose flex w-full flex-col dark:prose-invert">
  <p class=" m-0 text-sm font-semibold text-zinc-500 dark:text-zinc-300">
    {formattedDate}
  </p>
  <div class="flex flex-col gap-2">
    <a href={`/${slug}`} class="m-0 rounded no-underline">
      <h2 class="m-0 max-w-md hover:underline">{title}</h2>
    </a>
    <p class="m-0">{excerpt}</p>
  </div>
</div>

// src/components/BlogPreview.jsx

import Metadata from './Metadata'
import Tags from './Tags'

export default function BlogPreview({ post }){
    const { slug, title, excerpt, date, readtime, tags } = post
    const formattedDate = new Date(date).toDateString()

    return (
    <div className="prose dark:prose-invert flex flex-col gap-1">
        <h3 className=" text-zinc-400 m-0 font-bold">{formattedDate}</h3>
        <a href={`/${slug}`} className="no-underline m-0 rounded"> 
            <h1 className="hover:text-amber-900 m-0 dark:hover:text-amber-300">{title}</h1>
        </a>
        <p className="m-0">{excerpt}</p>
        <Metadata className="m-0" readtime={readtime} />
        <Tags className="m-0" tags={tags} />
    </div>
)}
