// src/components/Metadata.jsx
export default function Metadata({ filePath }) {
  return (
    <div className="flex flex-wrap gap-3 align-middle text-sm">
      <a
        id="gh-link"
        className="relative flex content-center items-center gap-1 no-underline"
        target="_blank"
        rel="noopener noreferrer"
        href={`https://github.com/pol-piella/polpiella.dev/edit/main/${filePath}`}>
        <img
          className="m-0 aspect-square w-5 dark:invert"
          src="/assets/github.svg"
        />
        <b>Found a mistake? Edit on Github!</b>
      </a>
    </div>
  )
}

// src/components/Metadata.svelte
<script>
  export let filePath
</script>

<div class="not-prose flex flex-wrap align-middle text-sm">
  <a
    id="gh-link"
    class="relative flex content-center items-center gap-1 no-underline hover:underline"
    target="_blank"
    rel="noopener noreferrer"
    href={`https://github.com/pol-piella/polpiella.dev/edit/main/${filePath}`}>
    <img
      class="m-0 aspect-square w-5 dark:invert"
      src="/assets/github.svg"
      alt="Github Logo" />
    <b>Found a mistake? Edit on Github!</b>
  </a>
</div>
