// src/components/Paginator.jsx
const Link = ({ url, children }) => (
  <a
    className="rounded bg-gray-300 p-2 font-bold transition-colors hover:bg-slate-300 dark:bg-gray-700 dark:hover:bg-slate-800"
    href={url}>
    {children}
  </a>
)

export default function Paginator({ previousURL, nextURL }) {
  return (
    <div className="mb-5 flex justify-start gap-3 dark:text-gray-100">
      {previousURL && <Link url={previousURL}>&larr; Newer Articles</Link>}
      {nextURL && <Link url={nextURL}>Older Articles &rarr;</Link>}
    </div>
  )
}

// src/components/Paginator.svelte
<script lang="ts">
  export let previousURL: string
  export let nextURL: string
</script>

<div class="flex justify-start gap-3 dark:text-gray-100">
  {#if previousURL != undefined}
    <a
      class="rounded bg-gray-300 p-2 font-bold transition-colors hover:bg-slate-300 dark:bg-gray-700 dark:hover:bg-slate-800"
      href={previousURL == '' ? '/' : previousURL}>
      &larr; Newer Articles
    </a>
  {/if}
  {#if nextURL}
    <a
      class="rounded bg-gray-300 p-2 font-bold transition-colors hover:bg-slate-300 dark:bg-gray-700 dark:hover:bg-slate-800"
      href={nextURL}>
      Older Articles &rarr;
    </a>
  {/if}
</div>
