// src/components/Timeline/Timeline.svelte
<script lang="ts">
  import TimelineEvent from '@components/Timeline/TimelineEvent.svelte'
  import type { Event } from './Event'

  export let events: Event[]
  export let title: string
</script>

<div>
  <p class="mb-8">{title}</p>
  <ul
    class="relative mx-2 list-none border-l border-gray-200 dark:border-gray-700">
    {#each events as event}
      <TimelineEvent {event} />
    {/each}
  </ul>
</div>

// src/components/Timeline.jsx
import TimelineEvent from '@components/TimelineEvent'

export default function Timeline({ title, events }) {
  return (
    <>
      <p className="mb-8">{title}</p>
      <ul className="relative mx-2 list-none border-l border-gray-200 dark:border-gray-700">
        {events.map((event, index) => (
          <TimelineEvent key={index} {...event} />
        ))}
      </ul>
    </>
  )
}
